In [1]:
import pandas as pd

In [2]:
baseline_df = pd.read_csv('baselineDF_full.csv')

In [11]:
baseline_df.drop('Unnamed: 0', axis = 1)

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,...,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,first_dep_time,total_add_gtime,longest_add_gtime,no_name
0,2018-12-01,NK,NK,NK,395,NK,N602NK,395,14100,PHL,...,2176.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-12-01,NK,NK,NK,396,NK,N602NK,396,12889,LAS,...,2176.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-12-01,NK,NK,NK,403,NK,N507NK,403,10397,ATL,...,581.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-12-01,NK,NK,NK,403,NK,N507NK,403,12892,LAX,...,1947.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-12-01,NK,NK,NK,404,NK,N512NK,404,10397,ATL,...,1947.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99087,2018-12-05,AA,AA_CODESHARE,AA,4874,PT,N642AE,4874,14574,ROA,...,155.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99088,2018-12-05,AA,AA_CODESHARE,AA,4875,PT,N669MB,4875,10135,ABE,...,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99089,2018-12-05,AA,AA_CODESHARE,AA,4876,PT,N672AE,4876,10721,BOS,...,335.0,7.0,0.0,0.0,0.0,46.0,NaN,NaN,NaN,NaN
99090,2018-12-05,AA,AA_CODESHARE,AA,4877,PT,N648AE,4877,13230,MDT,...,84.0,8.0,0.0,6.0,0.0,27.0,NaN,NaN,NaN,NaN
99091,2018-12-05,AA,AA_CODESHARE,AA,4877,PT,N648AE,4877,14100,PHL,...,84.0,0.0,16.0,17.0,0.0,0.0,NaN,NaN,NaN,NaN

In [21]:
carriers = baseline_df['op_unique_carrier'].unique().tolist()

In [46]:
carriers

['NK',
 'OH',
 'HA',
 'YV',
 'YX',
 'EV',
 'AA',
 'PT',
 'CP',
 'AS',
 'UA',
 'WN',
 'C5',
 'ZW',
 'AX',
 'G7',
 '9E',
 'B6',
 'DL',
 'G4',
 'MQ',
 'F9',
 'EM',
 'QX',
 'OO',
 'KS']

In [25]:
import psycopg2
con = psycopg2.connect(database="mid_term_project", user="lhl_student", password="lhl_student", host="mid-term-project.ca2jkepgjpne.us-east-2.rds.amazonaws.com", port="5432")
cur = con.cursor()

In [26]:
fuel = pd.read_sql_query('''SELECT * FROM fuel_comsumption;''', con)

In [31]:
passenger_fuel = fuel.loc[fuel['unique_carrier'].isin(carriers)]

In [59]:
passenger_fuel.groupby('unique_carrier').median()

,month,airline_id,carrier_group_new,sdomt_gallons,satl_gallons,spac_gallons,slat_gallons,sint_gallons,ts_gallons,tdomt_gallons,...,sdomt_cost,satl_cost,spac_cost,slat_cost,sint_cost,ts_cost,tdomt_cost,tint_cost,total_cost,year
unique_carrier,,,,,,,,,,,,,,,,,,,,,
9E,6.0,20363.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017.0
AA,6.0,19805.0,3.0,181028818.0,49277957.0,20612267.0,46807612.0,115912977.0,296927850.0,181550822.0,...,282005676.0,76327982.0,36726420.0,83505859.0,195764791.0,477838616.0,282820840.0,196062834.0,479414257.0,2017.0
AS,6.0,19930.0,3.0,41119033.0,0.0,0.0,848713.0,848713.0,41607550.0,41220414.0,...,75380569.0,0.0,0.0,1580523.0,1580523.0,76547773.0,75531736.0,1580523.0,76698940.0,2017.0
B6,6.0,20409.0,3.0,53163032.0,0.0,0.0,12900982.0,12900982.0,66674932.0,53163032.0,...,96765922.0,0.0,0.0,21486981.0,21486981.0,117320621.0,96789777.0,21486981.0,117338300.0,2017.0
CP,6.0,21167.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017.0
DL,6.0,19790.0,3.0,165835898.0,64779633.0,33197021.0,25557523.0,123922902.0,282495325.0,167433775.0,...,315405002.0,123775123.0,61426740.0,46854062.0,227460828.0,548903961.0,319643796.0,227521518.0,554695520.0,2017.0
EV,6.0,20366.0,3.0,77248.5,0.0,0.0,0.0,0.0,77248.5,77248.5,...,168596.0,0.0,0.0,0.0,0.0,168596.0,168596.0,0.0,168596.0,2017.0
F9,6.0,20436.0,3.0,18646834.0,0.0,0.0,1581768.0,1581768.0,20082594.0,18646834.0,...,28849738.0,0.0,0.0,2642423.0,2642423.0,31339648.0,28849738.0,2657571.0,31449921.0,2017.0
G4,6.0,20368.0,3.0,14198071.0,0.0,0.0,0.0,0.0,14198071.0,14585655.0,...,27515866.0,0.0,0.0,0.0,0.0,27515866.0,28784055.0,0.0,28784055.0,2017.0
G7,6.0,20500.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017.0
HA,6.0,19690.0,3.0,14833229.0,0.0,6699830.0,0.0,6699830.0,21544924.0,14868907.0,...,25212804.0,0.0,11392851.0,0.0,11392851.0,36605655.0,25358483.0,11400591.0,36759074.0,2017.0
MQ,6.0,20398.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017.0
NK,6.0,20416.0,3.0,25669048.0,0.0,0.0,2371022.0,2371022.0,27840616.0,25669048.0,...,44644241.0,0.0,0.0,4173785.0,4173785.0,48152344.0,44644241.0,4173785.0,48152344.0,2017.0
OH,6.0,20397.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017.0
OO,6.0,20304.0,3.0,6548860.0,0.0,0.0,0.0,0.0,6548860.0,6548860.0,...,12279100.0,0.0,0.0,0.0,0.0,12279100.0,12279100.0,0.0,12279100.0,2017.0
QX,6.0,19687.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017.0
UA,6.0,19977.0,3.0,132234279.0,65873770.0,55012275.0,28091245.0,143998219.0,277021464.0,133758006.0,...,223503554.0,107288108.0,96189441.0,51133865.0,251848905.0,470782228.0,225059256.0,253280423.0,472939819.0,2017.0
WN,6.0,19393.0,3.0,167617869.0,0.0,0.0,1559242.0,1559242.0,169465543.0,167929798.0,...,314227028.0,0.0,0.0,3228252.0,3228252.0,318784662.0,314713847.0,3228252.0,319188062.0,2017.0
YV,6.0,20378.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017.0
YX,6.0,20452.0,2.0,28582.0,0.0,0.0,0.0,0.0,28582.0,28582.0,...,72538.0,0.0,0.0,0.0,0.0,72538.0,72538.0,0.0,72538.0,2017.0
ZW,6.5,20046.0,2.0,5947620.5,0.0,0.0,0.0,0.0,5947620.5,5947620.5,...,7634273.5,0.0,0.0,0.0,0.0,7634273.5,7634273.5,0.0,7634273.5,2016.0

In [55]:
passenger_fuel.corr()

,month,airline_id,carrier_group_new,sdomt_gallons,satl_gallons,spac_gallons,slat_gallons,sint_gallons,ts_gallons,tdomt_gallons,...,sdomt_cost,satl_cost,spac_cost,slat_cost,sint_cost,ts_cost,tdomt_cost,tint_cost,total_cost,year
month,1.000000,-0.000446,-0.005598,0.015283,0.028892,0.002402,-0.023069,0.008168,0.012967,0.015286,...,0.014411,0.025204,-0.000518,-0.022757,0.005617,0.011317,0.014474,0.005491,0.011299,-0.104523
airline_id,-0.000446,1.000000,-0.367123,-0.612955,-0.354887,-0.347089,-0.342840,-0.366486,-0.537508,-0.612457,...,-0.603885,-0.345929,-0.342159,-0.341931,-0.360489,-0.530264,-0.603263,-0.360365,-0.529724,0.007775
carrier_group_new,-0.005598,-0.367123,1.000000,0.492744,0.310873,0.316216,0.368745,0.343192,0.453866,0.492660,...,0.484167,0.300306,0.309076,0.366339,0.335427,0.445930,0.484009,0.335421,0.445692,0.056496
sdomt_gallons,0.015283,-0.612955,0.492744,1.000000,0.769583,0.676315,0.793332,0.784689,0.960630,0.999982,...,0.976844,0.748007,0.667742,0.787913,0.770697,0.941786,0.976844,0.770402,0.941262,0.057282
satl_gallons,0.028892,-0.354887,0.310873,0.769583,1.000000,0.927008,0.845037,0.984430,0.909844,0.771408,...,0.742868,0.975438,0.914902,0.840137,0.967732,0.887179,0.745419,0.967490,0.887876,0.020844
spac_gallons,0.002402,-0.347089,0.316216,0.676315,0.927008,1.000000,0.764595,0.950760,0.837959,0.678474,...,0.644651,0.893134,0.974307,0.753935,0.923488,0.807382,0.647486,0.923625,0.808421,-0.004632
slat_gallons,-0.023069,-0.342840,0.368745,0.793332,0.845037,0.764595,1.000000,0.903067,0.887839,0.794225,...,0.743935,0.802537,0.740547,0.977476,0.869993,0.844044,0.744888,0.869755,0.843883,0.022648
sint_gallons,0.008168,-0.366486,0.343192,0.784689,0.984430,0.950760,0.903067,1.000000,0.926021,0.786454,...,0.749050,0.950985,0.930675,0.891415,0.974833,0.894136,0.751382,0.974697,0.894741,0.014512
ts_gallons,0.012967,-0.537508,0.453866,0.960630,0.909844,0.837959,0.887839,0.926021,1.000000,0.961410,...,0.930556,0.881715,0.823736,0.879317,0.906221,0.974235,0.931601,0.905980,0.974187,0.041385
tdomt_gallons,0.015286,-0.612457,0.492660,0.999982,0.771408,0.678474,0.794225,0.786454,0.961410,1.000000,...,0.976720,0.749751,0.669820,0.788645,0.772354,0.942452,0.976757,0.772063,0.941951,0.056934
tint_gallons,0.008082,-0.366400,0.343205,0.784493,0.984334,0.951036,0.902911,0.999998,0.925901,0.786262,...,0.748909,0.950929,0.930990,0.891315,0.974876,0.894069,0.751245,0.974745,0.894678,0.014324
total_gallons,0.012930,-0.537097,0.453721,0.960248,0.910348,0.838823,0.887833,0.926522,0.999993,0.961051,...,0.930157,0.882209,0.824583,0.879246,0.906693,0.974203,0.931225,0.906457,0.974170,0.041101
sdomt_cost,0.014411,-0.603885,0.484167,0.976844,0.742868,0.644651,0.743935,0.749050,0.930556,0.976720,...,1.000000,0.764558,0.676969,0.780417,0.779313,0.959786,0.999977,0.779138,0.959304,0.105000
satl_cost,0.025204,-0.345929,0.300306,0.748007,0.975438,0.893134,0.802537,0.950985,0.881715,0.749751,...,0.764558,1.000000,0.928418,0.839840,0.983395,0.907441,0.767118,0.983269,0.908189,0.049061
spac_cost,-0.000518,-0.342159,0.309076,0.667742,0.914902,0.974307,0.740547,0.930675,0.823736,0.669820,...,0.676969,0.928418,1.000000,0.770973,0.952627,0.840171,0.679806,0.952909,0.841259,0.021423
slat_cost,-0.022757,-0.341931,0.366339,0.787913,0.840137,0.753935,0.977476,0.891415,0.879317,0.788645,...,0.780417,0.839840,0.770973,1.000000,0.903013,0.881115,0.781280,0.902903,0.880936,0.059871
sint_cost,0.005617,-0.360489,0.335427,0.770697,0.967732,0.923488,0.869993,0.974833,0.906221,0.772354,...,0.779313,0.983395,0.952627,0.903013,1.000000,0.923890,0.781622,0.999996,0.924527,0.045961
ts_cost,0.011317,-0.530264,0.445930,0.941786,0.887179,0.807382,0.844044,0.894136,0.974235,0.942452,...,0.959786,0.907441,0.840171,0.881115,0.923890,1.000000,0.960806,0.923782,0.999991,0.084709
tdomt_cost,0.014474,-0.603263,0.484009,0.976844,0.745419,0.647486,0.744888,0.751382,0.931601,0.976757,...,0.999977,0.767118,0.679806,0.781280,0.781622,0.960806,1.000000,0.781452,0.960352,0.104477
tint_cost,0.005491,-0.360365,0.335421,0.770402,0.967490,0.923625,0.869755,0.974697,0.905980,0.772063,...,0.779138,0.983269,0.952909,0.902903,0.999996,0.923782,0.781452,1.000000,0.924424,0.045698
total_cost,0.011299,-0.529724,0.445692,0.941262,0.887876,0.808421,0.843883,0.894741,0.974187,0.941951,...,0.959304,0.908189,0.841259,0.880936,0.924527,0.999991,0.960352,0.924424,1.000000,0.084274
year,-0.104523,0.007775,0.056496,0.057282,0.020844,-0.004632,0.022648,0.014512,0.041385,0.056934,...,0.105000,0.049061,0.021423,0.059871,0.045961,0.084709,0.104477,0.045698,0.084274,1.000000

In [154]:
fuel_carrier = passenger_fuel[['unique_carrier', 'airline_id', 'total_cost']].groupby('unique_carrier').median().rename({'unique_carrier':'op_unique_carrier'})

In [67]:
baseline_df.columns

Index(['Unnamed: 0', 'fl_date', 'mkt_unique_carrier', 'branded_code_share',
       'mkt_carrier', 'mkt_carrier_fl_num', 'op_unique_carrier', 'tail_num',
       'op_carrier_fl_num', 'origin_airport_id', 'origin', 'origin_city_name',
       'dest_airport_id', 'dest', 'dest_city_name', 'crs_dep_time', 'dep_time',
       'dep_delay', 'taxi_out', 'wheels_off', 'wheels_on', 'taxi_in',
       'crs_arr_time', 'arr_time', 'arr_delay', 'cancelled',
       'cancellation_code', 'diverted', 'dup', 'crs_elapsed_time',
       'actual_elapsed_time', 'air_time', 'flights', 'distance',
       'carrier_delay', 'weather_delay', 'nas_delay', 'security_delay',
       'late_aircraft_delay', 'first_dep_time', 'total_add_gtime',
       'longest_add_gtime', 'no_name'],
      dtype='object')

In [128]:
mapping2 = {'dep_delay':'mean_dep_delay', 'arr_delay':'mean_arr_delay', 'distance':'mean_distance'}
mapping3 = {'dep_delay':'med_dep_delay', 'arr_delay':'med_arr_delay', 'distance':'med_distance'}

In [129]:
base_del_mean =baseline_df[['op_unique_carrier', 'dep_delay', 'arr_delay', 'distance']].groupby('op_unique_carrier').mean().rename(mapping2, axis = 1)

In [130]:
base_del_med = baseline_df[['op_unique_carrier', 'dep_delay', 'arr_delay', 'distance']].groupby('op_unique_carrier').median().rename(mapping3, axis = 1)

In [131]:
base_del_med

                   med_dep_delay  med_arr_delay  med_distance
op_unique_carrier
9E                          -5.0          -12.0         427.0
AA                          -3.0           -6.0         868.0
AS                          -6.0          -10.0         987.0
AX                          -4.0           -3.0         488.0
B6                          -4.0           -5.0         997.0
C5                          -1.5            3.5         325.0
CP                          -4.0           -6.0         386.0
DL                          -3.0          -11.0         669.0
EM                          -8.0           -9.0          72.0
EV                          -4.0           -3.0         427.0
F9                          -4.0           -5.0        1013.0
G4                          -5.0           -8.0         932.0
G7                          -5.0           -9.0         491.0
HA                          -6.0           -6.0         163.0
KS                           5.5            7.5         792.0
MQ                          -3.0           -2.0         343.0
NK                          -4.0           -9.0         980.0
OH                          -3.0           -5.0         370.0
OO                          -4.0           -4.0         417.0
PT                          -4.0           -7.0         212.0
QX                          -3.0           -4.0         287.0
UA                          -4.0           -5.0         967.0
WN                          -1.0           -7.0         632.0
YV                          -3.0           -3.0         489.0
YX                          -5.0           -6.0         500.0
ZW                          -4.0            0.0         315.0

In [123]:
mapping = {'carrier_delay':'mean_carr', 'weather_delay':'mean_weather', 'nas_delay':'mean_nas', 'security_delay':'mean_sec', 'late_aircraft_delay':'mean_late_air'}

In [124]:
base_types_mean = baseline_df[['op_unique_carrier','carrier_delay', 'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay']].groupby('op_unique_carrier').mean().rename(mapping, axis = 1)

In [91]:
baseline_df['is_arr_delayed'] = 0
baseline_df['is_arr_delayed'].loc[baseline_df['arr_delay'] >= 15] = 1

G:\Programming\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [101]:
baseline_percdel = baseline_df[['op_unique_carrier', 'is_arr_delayed']].groupby('op_unique_carrier').mean().rename({'is_arr_delayed':'perc_del'}, axis = 1)

In [139]:
baseline_percdel.head()

                   perc_del
op_unique_carrier
9E                 0.175563
AA                 0.161396
AS                 0.131091
AX                 0.267635
B6                 0.245564

In [140]:
base_del_mean.head()

                   mean_dep_delay  mean_arr_delay  mean_distance
op_unique_carrier
9E                      10.032154        1.370418     482.820900
AA                       4.477335        0.478158     975.205995
AS                      -0.662370       -6.086136    1329.635335
AX                      11.399378       11.263485     497.609959
B6                      12.338727        9.930585    1068.144833

In [134]:
base_del_med.shape

(26, 3)

In [135]:
base_types_mean.shape

(26, 5)

In [141]:
merge1 = baseline_percdel.merge(base_del_mean, left_index = True, right_index = True)

In [142]:
merge2 = merge1.merge(base_del_med, left_index = True, right_index = True)

In [143]:
merge3 = merge2.merge(base_types_mean, left_index = True, right_index = True)

In [159]:
merge3.head()

,perc_del,mean_dep_delay,mean_arr_delay,mean_distance,med_dep_delay,med_arr_delay,med_distance,mean_carr,mean_weather,mean_nas,mean_sec,mean_late_air
op_unique_carrier,,,,,,,,,,,,
9E,0.175563,10.032154,1.370418,482.820900,-5.0,-12.0,427.0,22.102564,4.846154,21.575092,0.000000,31.727106
AA,0.161396,4.477335,0.478158,975.205995,-3.0,-6.0,868.0,18.089468,1.100793,14.731597,0.100793,15.976217
AS,0.131091,-0.662370,-6.086136,1329.635335,-6.0,-10.0,987.0,11.786571,0.458034,22.398082,0.153477,9.659472
AX,0.267635,11.399378,11.263485,497.609959,-4.0,-3.0,488.0,15.775194,0.961240,13.414729,0.000000,35.251938
B6,0.245564,12.338727,9.930585,1068.144833,-4.0,-5.0,997.0,23.978746,0.296493,20.357067,0.140276,26.226355

In [151]:
fuel_carrier.shape

(21, 2)

In [171]:
carrier_flight_fuel = merge3.merge(fuel_carrier, how = 'outer', left_index = True, right_index = True).drop('airline_id', axis = 1).fillna(0)

In [172]:
carrier_flight_fuel

,perc_del,mean_dep_delay,mean_arr_delay,mean_distance,med_dep_delay,med_arr_delay,med_distance,mean_carr,mean_weather,mean_nas,mean_sec,mean_late_air,total_cost
9E,0.175563,10.032154,1.370418,482.820900,-5.0,-12.0,427.0,22.102564,4.846154,21.575092,0.000000,31.727106,0.0
AA,0.161396,4.477335,0.478158,975.205995,-3.0,-6.0,868.0,18.089468,1.100793,14.731597,0.100793,15.976217,479414257.0
AS,0.131091,-0.662370,-6.086136,1329.635335,-6.0,-10.0,987.0,11.786571,0.458034,22.398082,0.153477,9.659472,76698940.0
AX,0.267635,11.399378,11.263485,497.609959,-4.0,-3.0,488.0,15.775194,0.961240,13.414729,0.000000,35.251938,0.0
B6,0.245564,12.338727,9.930585,1068.144833,-4.0,-5.0,997.0,23.978746,0.296493,20.357067,0.140276,26.226355,117338300.0
C5,0.399371,32.558176,31.734277,419.628931,-1.5,3.5,325.0,22.795276,0.401575,26.834646,0.000000,42.511811,0.0
CP,0.233283,17.145137,13.256839,531.106383,-4.0,-6.0,386.0,33.078176,4.729642,10.524430,0.000000,42.570033,0.0
DL,0.102581,2.536495,-6.698093,852.178202,-3.0,-11.0,669.0,17.544071,2.367788,19.869391,0.000000,11.663462,554695520.0
EM,0.000000,-7.658537,-8.170732,71.512195,-8.0,-9.0,72.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
EV,0.270863,16.150691,15.674297,445.662375,-4.0,-3.0,427.0,28.478873,0.406690,27.684859,0.000000,24.723592,168596.0
F9,0.252433,11.445814,8.245944,1081.577547,-4.0,-5.0,1013.0,21.951157,0.043702,19.503856,0.000000,24.159383,31449921.0
G4,0.171558,3.230248,1.485327,906.969526,-5.0,-8.0,932.0,20.019737,6.342105,11.118421,0.000000,21.763158,28784055.0
G7,0.227390,11.434970,5.640827,511.899225,-5.0,-9.0,491.0,20.750000,5.352273,14.768939,0.000000,31.359848,0.0
HA,0.069665,-2.558201,-3.606702,713.395062,-6.0,-6.0,163.0,19.582278,0.746835,0.417722,0.000000,9.746835,36759074.0
KS,0.375000,14.625000,14.250000,792.000000,5.5,7.5,792.0,9.166667,0.000000,22.500000,0.000000,10.833333,0.0
MQ,0.259944,8.258404,8.232230,412.026944,-3.0,-2.0,343.0,12.506417,5.167818,14.828233,0.006910,20.785785,0.0
NK,0.107507,2.478221,-3.201576,1021.204819,-4.0,-9.0,980.0,13.357759,0.810345,37.116379,0.000000,9.271552,48152344.0
OH,0.162370,6.476687,2.360943,395.771805,-3.0,-5.0,370.0,15.809122,1.966216,11.868243,0.201014,28.817568,0.0
OO,0.248767,11.529493,9.782699,496.022292,-4.0,-4.0,417.0,19.865186,5.806503,17.278351,0.100714,26.506344,12279100.0
PT,0.258581,13.956522,10.717010,251.333333,-4.0,-7.0,212.0,15.064897,6.206490,11.640118,0.008850,39.737463,0.0
QX,0.180645,5.879355,3.766452,383.247742,-3.0,-4.0,287.0,14.275000,2.596429,10.703571,0.142857,23.567857,0.0
UA,0.190905,7.002189,4.239908,1158.477991,-4.0,-5.0,967.0,14.628025,1.299363,22.812102,0.000000,20.503822,472939819.0
WN,0.120451,3.986880,-2.455150,743.451647,-1.0,-7.0,632.0,14.620010,0.395269,9.763923,0.234105,15.159685,319188062.0
YV,0.207056,9.655381,8.848895,569.443336,-3.0,-3.0,489.0,32.163511,1.437177,8.497418,0.027539,24.127367,0.0
YX,0.191092,5.196360,2.342433,580.594588,-5.0,-6.0,500.0,13.615288,1.676692,21.983709,0.002506,18.006266,72538.0
ZW,0.289644,10.339806,12.612460,363.173139,-4.0,0.0,315.0,17.541899,2.145251,18.628492,0.000000,26.251397,7634273.5